spring.application.name=RegistrationLogin

spring.datasource.url=jdbc:mysql://localhost:3306/springthym
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8090
